# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Máquina vulnerable (Ubuntu con Docker, agente Wazuh y Suricata)
  config.vm.define "vulnerable" do |vulnerable|
    vulnerable.vm.box = "ubuntu/jammy64"
    vulnerable.vm.network "private_network", ip: "192.168.30.30"
    vulnerable.vm.hostname = "vulnerable"
    vulnerable.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    # Sincronizar archivos locales (docker-compose.yml, suricata.yaml)
    vulnerable.vm.synced_folder ".", "/vagrant"
    # Script de configuración del agente de wazuh y la integración de suricata.
    vulnerable.vm.provision "shell", path: "provision/vulnerable.sh", privileged: true,
      env: { "WAZUH_MANAGER_IP" => "192.168.30.20", "ATTACKER_IP" => "192.168.30.10" }
  end
end