# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "colddbox" do |colddbox|
    colddbox.vm.box = "colddbox-final"          # Nombre de la maquina
    colddbox.vm.network "private_network", ip: "192.168.30.31" # IP fija única
    colddbox.vm.hostname = "colddbox"
    colddbox.vm.network "forwarded_port", guest: 22, host: 2203, id: "ssh"
    colddbox.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.gui = false                     # Puede cambiarse por true si se quiere visualizar la maquina pero no es necesario para el laboratorio
    end
    # Sincronizar la carpeta actual (que contiene el Vagrantfile y 'provision/')
    colddbox.vm.synced_folder ".", "/vagrant"

    colddbox.vm.provision "shell", path: "provision/colddbox.sh", privileged: true,
      env: { "WAZUH_MANAGER_IP" => "192.168.30.20", "ATTACKER_IP" => "192.168.30.10" }
  end
end